In [10]:
import pandas as pd
df = pd.read_csv('data 10.csv')

**Описание данных:**
- id - уникальный идентификатор заведения
- address - физический адрес заведения
- categories - категории заведения (например, "Fast food restaurant").
- city - город, в котором заведение находится.
- cuisines - кухни, которые практикуются в заведении. Например "Mexican".
- dateAdded - дата добавления записи. Будем считать, что она совпадает с датой открытия заведения.
- dateUpdated - дата обновления информации о заведении.
- latitude - географическая широта.
- longitude - географическая долгота.
- menus.category - категории пищи в меню.
- menus.currency - валюта, в которой принимают оплату.
- menus.dateSeen - дата, когда было заведено это меню.
- menus.description - описание меню от заведения.
- menus.name - название меню.
- name - название заведения.
- province - область (штат), где находится заведение.

В качестве первого шага давайте посмотрим на наши данные c помощью метода head()

In [2]:
df.head()

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
0,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02T11:49:34Z,2017-02-01T18:04:44Z,39.561570,-95.121020,NaN,NaN,2017-02-01T18:04:44Z,NaN,Taco,Gambino's Pizza,KS
1,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02T11:49:34Z,2017-02-01T18:04:44Z,39.561570,-95.121020,NaN,NaN,2016-03-02T11:49:34Z,"Beef, onion, cheddar cheese, lettuce, refried...",Taco,Gambino's Pizza,KS
2,AVwc__dF_7pvs4fz1Ncy,9521 Morton Davis Dr,"Golf Course, American Restaurant, and Resort",Patterson,NaN,2016-10-14T01:58:25Z,2016-10-14T01:58:25Z,37.401855,-121.266703,NaN,NaN,2016-10-14T01:58:25Z,"Beef barbacoa or chicken, spanish rice, pico d...",Smotherd Burrito,Diablo Grande Golf & Country Club,Grayson
3,AVwc__kCByjofQCxkdm-,10550 W I 25 Frontage Rd,Fast Food Restaurant,Longmont,NaN,2016-09-09T17:30:34Z,2016-10-04T05:15:17Z,NaN,NaN,NaN,NaN,2016-09-09T17:30:34Z,NaN,Sausage Burrito,Mcdonald's,Niwot
4,AVwc__WtByjofQCxkdkR,8495 W 3rd St,"Mexican Restaurant Mid-City West,Mexican Resta...",Los Angeles,Mexican,2016-05-19T11:50:25Z,2016-09-11T00:06:37Z,34.080724,-118.389578,NaN,NaN,2016-05-19T11:50:25Z,"Wahoo, avocado, cabbage, pico de gallo and av...",Wahoo Tacogrilled,Baja Fresh Mexican Grill,Bicentennial

Давайте посмотрим, какой тип имеют колонки city и latitude

In [4]:
import numpy as np
print(np.dtype(df['city']), np.dtype(df['latitude']))

object float64

Какие колонки будут выведены при применении метода describe

In [5]:
df.describe()
# latitude and longitude because its real-type columns

           latitude     longitude
count  55636.000000  55636.000000
mean      36.694846    -98.713309
std        4.835124     18.245857
min      -31.986438   -159.492690
25%       33.668355   -117.647150
50%       36.047195    -96.682320
75%       40.588380    -82.679930
max       61.219460    115.903696

Сейчас в данных присутствуют пропущенные значения. Давайте их удалим.
Примените метод dropna.  Сколько осталось записей?

In [7]:
df = df.dropna()
# 1925

Отберите заведения, которые находятся в городе Калифорния ('California'), штат Миссури.

In [11]:
df[df['city'] == 'California']

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
40483,AVwdBeyk_7pvs4fz1cwP,308 S Oak St,"Gas Station,Convenience Stores,Grocery Stores,...",California,Pizza,2016-04-02T05:28:33Z,2016-09-14T02:53:47Z,38.630528,-92.566433,NaN,USD,"2016-04-02T05:28:33Z,2016-09-14T02:53:47Z",NaN,Breakfast Burrito,Casey's General Store,MO
52930,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.631220,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,"A crunchy, red corn tortilla shell, filled wit...",Volcano Taco,Taco Bell,MO
52931,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.631220,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,NaN,Volcano Burrito,Taco Bell,MO
52932,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.631220,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,NaN,Soft Taco Supreme Beef,Taco Bell,MO
52933,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.631220,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,NaN,Grilled Chicken Burrito,Taco Bell,MO
52934,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.631220,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,"A warm, soft flour tortilla filled with authen...",Fresco Grilled Steak Soft Taco,Taco Bell,MO
52935,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.631220,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,"A crunchy, corn taco shell filled with seasone...",Fresco Crunchy Taco,Taco Bell,MO
52936,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.631220,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,NaN,Fresco Burrito Supreme Chicken,Taco Bell,MO
52937,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.631220,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,A crunchy taco made with premium seasoned beef...,Doritos Locos Tacos,Taco Bell,MO
52938,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.631220,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,"A crunchy, corn taco shell filled with seasone...",Crunchy Taco Supreme,Taco Bell,MO
52939,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.631220,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,"A crunchy, corn taco shell filled with seasone...",Crunchy Taco,Taco Bell,MO
65070,AVwdvUhykufWRAb58z0G,1002 W Buchanan St,Fast Food Restaurant,California,Take Out Restaurants,2015-11-06T10:12:53Z,2016-05-05T00:55:58Z,38.630332,-92.579018,NaN,NaN,"2016-04-02T05:28:16Z,2015-11-06T10:12:53Z","Spice up your morning with peppers, onions, fl...",Sausage Burrito,Mcdonald's,MO

Отберите заведения Taco Bell в городе Калифорния ('California'), штат Миссури.

In [12]:
df[(df['city'] == 'California') & (df['name'] == 'Taco Bell')]

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
52930,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.63122,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,"A crunchy, red corn tortilla shell, filled wit...",Volcano Taco,Taco Bell,MO
52931,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.63122,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,NaN,Volcano Burrito,Taco Bell,MO
52932,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.63122,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,NaN,Soft Taco Supreme Beef,Taco Bell,MO
52933,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.63122,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,NaN,Grilled Chicken Burrito,Taco Bell,MO
52934,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.63122,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,"A warm, soft flour tortilla filled with authen...",Fresco Grilled Steak Soft Taco,Taco Bell,MO
52935,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.63122,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,"A crunchy, corn taco shell filled with seasone...",Fresco Crunchy Taco,Taco Bell,MO
52936,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.63122,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,NaN,Fresco Burrito Supreme Chicken,Taco Bell,MO
52937,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.63122,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,A crunchy taco made with premium seasoned beef...,Doritos Locos Tacos,Taco Bell,MO
52938,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.63122,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,"A crunchy, corn taco shell filled with seasone...",Crunchy Taco Supreme,Taco Bell,MO
52939,AVwdKTFqIN2L1WUfs1SP,1020 W Buchanan St,"Fast Food Restaurant and Mexican Restaurant,Me...",California,NaN,2015-12-02T19:29:16Z,2016-05-05T00:56:00Z,38.63122,-92.580769,NaN,NaN,2016-04-02T05:28:11Z,"A crunchy, corn taco shell filled with seasone...",Crunchy Taco,Taco Bell,MO

Давайте найдем заведения Taco Bell или заведения, которые находятся в городе Нью-Йорк. При этом обязательно, чтобы в названии меню не было Volcano Taco и Fresco Soft Taco (именно таких значений колонки). Данные нужно сохранить в датафрейм result.
Данные загружены в переменную data.

In [15]:
result = df[((df['name'] == 'Taco Bell') | (df['city'] == 'New York')) & (df['name'] != 'Volcano Taco') & \
            (df['name'] != 'Fresco Soft Taco')]
result

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
130,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Volcano Taco,Taco Bell,NH
131,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Volcano Burrito,Taco Bell,NH
132,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Taco 12 Pack,Taco Bell,NH
133,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Grilled Steak Soft Taco,Taco Bell,NH
134,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Fresco Soft Taco,Taco Bell,NH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76904,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Tacos,USD,2016-08-21T00:00:00Z,NaN,Trio of Tacos,Hell's Kitchen,Nyc
76905,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,"Huevos, Etc.",USD,2016-08-07T00:00:00Z,NaN,Brunch Burrito,Hell's Kitchen,Nyc
76906,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Botanas,USD,2016-08-07T00:00:00Z,NaN,Grilled Chicken Mini Burrito,Hell's Kitchen,Nyc
76907,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Botanas,USD,2016-08-07T00:00:00Z,with pumpkin seed guacamole,Grilled Vegetable Mini Burrito,Hell's Kitchen,Nyc
76908,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Main,NaN,2016-08-21T00:00:00Z,NaN,Burritos,Hell's Kitchen,Nyc

Давайте отберем рестораны, где значение валюты, в которой принимают оплату, не пропущено

In [16]:
df[~(df['menus.currency'].isna())]

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
15,AVwc_1y6kufWRAb51O6w,906 Park Ave SW,"Coffee Shop,Restaurants,Coffeehouses",Albuquerque,Coffee Shops,2016-06-05T20:15:56Z,2017-07-06T13:28:29Z,35.085320,-106.657616,NaN,USD,"2016-06-05T20:15:56Z,2016-10-20T07:09:38Z","Potatoes, onion, peppers, mushroom, avocado, b...",Mondo Veggie Burrito,Java Joe's,NM
16,AVwc_1y6kufWRAb51O6w,906 Park Ave SW,"Coffee Shop,Restaurants,Coffeehouses",Albuquerque,Coffee Shops,2016-06-05T20:15:56Z,2017-07-06T13:28:29Z,35.085320,-106.657616,NaN,USD,"2016-06-05T20:15:56Z,2016-10-20T07:09:38Z","Grilled tofu, potatoes and your choice of chil...",Tofu Burrito,Java Joe's,NM
17,AVwc_1y6kufWRAb51O6w,906 Park Ave SW,"Coffee Shop,Restaurants,Coffeehouses",Albuquerque,Coffee Shops,2016-06-05T20:15:56Z,2017-07-06T13:28:29Z,35.085320,-106.657616,NaN,USD,"2016-06-05T20:15:56Z,2016-10-20T07:09:38Z",NaN,Black Bean Burrito,Java Joe's,NM
18,AVwc_2OQ_7pvs4fz1L5H,100 W Higgins Rd,Restaurant,Barrington,"Mexican, Latin American",2016-07-26T17:39:41Z,2016-08-26T05:25:56Z,42.074974,-88.189151,NaN,USD,2016-08-22T00:00:00Z,NaN,Burrito De Rajas,Mago Grill & Cantina - South Barrington,Fox Rv Vly Gn
19,AVwc_2OQ_7pvs4fz1L5H,100 W Higgins Rd,Restaurant,Barrington,"Mexican, Latin American",2016-07-26T17:39:41Z,2016-08-26T05:25:56Z,42.074974,-88.189151,NaN,USD,2016-08-22T00:00:00Z,"lettuce, chihuahua cheese, black beans, mexica...",Taco,Mago Grill & Cantina - South Barrington,Fox Rv Vly Gn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77255,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"meat, rice, beans, guacamole, sour cream, chee...",Super Burrito,La Casona Taqueria,California
77256,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"melted cheese, rice, beans & salsa",Steamed Broccoli Burrito,La Casona Taqueria,California
77257,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,meat & salsa,Regular Taco,La Casona Taqueria,California
77258,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"meat, rice, beans & salsa",Regular Burrito,La Casona Taqueria,California
77259,AVzRLlQNLD2H7whiWdH_,3919 24th St.,Restaurant,San Francisco,Mexican,2017-06-22T19:01:33Z,2017-06-22T19:01:33Z,37.751392,-122.430180,NaN,USD,2017-06-22T16:40:06.448Z,"stuffed with rice, beans, meat, topped with en...",Azteca Burrito,La Casona Taqueria,California

Напишите через запятую и пробел 5 городов с наибольшим количеством записей.

In [17]:
df['city'].value_counts().head()

San Diego        1924
Los Angeles      1603
Chicago          1186
San Francisco    1120
New York         1085
Name: city, dtype: int64

Посчитайте, сколько ресторанов Taco Bell находится в каждом городе. Отберите 5 городов, в которых ресторан встречается чаще всего. Количество ресторанов для этих городов с их названиями сохраните в виде объекта pd.Series

In [18]:
df[df['name'] == 'Taco Bell']['city'].value_counts().head()

Indianapolis        84
Columbus            63
Charleston          63
Tampa               62
South Lake Tahoe    42
Name: city, dtype: int64

Давайте найдем рестораны, открытые в октябре.
Отправьте индексы первых пяти ресторанов через запятую и пробел в порядке возрастания.

In [21]:
df['dateAdded'] = pd.to_datetime(df['dateAdded'])
df[df['dateAdded'].dt.month == 10].head()

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
2,AVwc__dF_7pvs4fz1Ncy,9521 Morton Davis Dr,"Golf Course, American Restaurant, and Resort",Patterson,NaN,2016-10-14 01:58:25+00:00,2016-10-14T01:58:25Z,37.401855,-121.266703,NaN,NaN,2016-10-14T01:58:25Z,"Beef barbacoa or chicken, spanish rice, pico d...",Smotherd Burrito,Diablo Grande Golf & Country Club,Grayson
21,AVwc_3Kp_7pvs4fz1MDQ,116 Pleasant St,"Restaurant,Seafood Restaurants,Take Out Restau...",Easthampton,"American,Seafood Restaurants",2015-10-26 23:10:06+00:00,2016-09-19T17:41:29Z,42.273525,-72.663124,NaN,USD,2016-09-19T17:41:29Z,"Crispy house-smoked pork belly, hoisin sauce, ...",Korean Pork Belly Tacos,Riff's Joint,Westhampton
22,AVwc_3Kp_7pvs4fz1MDQ,116 Pleasant St,"Restaurant,Seafood Restaurants,Take Out Restau...",Easthampton,"American,Seafood Restaurants",2015-10-26 23:10:06+00:00,2016-09-19T17:41:29Z,42.273525,-72.663124,NaN,USD,2016-09-19T17:41:29Z,"Black beans, corn and black bean salsa, guacam...",Speedy Gonzalez Burrito,Riff's Joint,Westhampton
23,AVwc_3Kp_7pvs4fz1MDQ,116 Pleasant St,"Restaurant,Seafood Restaurants,Take Out Restau...",Easthampton,"American,Seafood Restaurants",2015-10-26 23:10:06+00:00,2016-09-19T17:41:29Z,42.273525,-72.663124,NaN,USD,2016-09-19T17:41:29Z,"Black beans, jasmine rice and peanut slaw",Thai Dyed Burrito,Riff's Joint,Westhampton
24,AVwc_3Kp_7pvs4fz1MDQ,116 Pleasant St,"Restaurant,Seafood Restaurants,Take Out Restau...",Easthampton,"American,Seafood Restaurants",2015-10-26 23:10:06+00:00,2016-09-19T17:41:29Z,42.273525,-72.663124,NaN,USD,2016-09-19T17:41:29Z,"Black beans, cheddar, salsa, rice, sour cream,...",Burrito Supreme,Riff's Joint,Westhampton

Сделайте группировку по месяцу открытия ресторана (переменная dateAdded). Сколько ресторанов было открыто в каждом месяце? Рассчитайте по количеству уникальных id ресторанов в каждом месяце. Значения dateAdded должны при этом быть индексами.

In [22]:
df.groupby(df['dateAdded'].dt.month)['id'].count()

dateAdded
1      1258
2       994
3     20611
4     12171
5      4433
6      5536
7      2315
8      1542
9      1893
10    19542
11     5891
12     1074
Name: id, dtype: int64

В этом задании нужно добавить столбец update_deltaс количеством целых дней, полученных от разницы между dateUpdated и dateAdded.

Потом для каждого города найдите (в указанном порядке):

- среднее по переменной update_delta

- широту самой северной закусочной (чем севернее располжоена закусочная, тем больше будет значение широты)

In [24]:
df['update_delta'] = (pd.to_datetime(df['dateUpdated']) - df['dateAdded']).dt.days

In [26]:
df.groupby('city')['update_delta'].mean()

city
Abbeville       114.857143
Aberdeen         81.625000
Abilene         206.454545
Abingdon        303.500000
Abington        393.000000
                   ...
Zebulon           0.000000
Zephyr Cove     105.500000
Zephyrhills     329.695652
Zieglerville    621.000000
Zionsville      151.500000
Name: update_delta, Length: 3601, dtype: float64

In [27]:
df.groupby('city')['latitude'].max()

city
Abbeville       29.982108
Aberdeen        46.975110
Abilene         32.453090
Abingdon        36.712800
Abington        40.124851
                  ...
Zebulon         33.102090
Zephyr Cove     38.984947
Zephyrhills     28.271183
Zieglerville    40.291611
Zionsville      39.954970
Name: latitude, Length: 3601, dtype: float64

Отберите рестораны, у которых в колонке categories упоминается Pizza

In [28]:
df[df['categories'].apply(lambda x: x.find('Pizza') >= 0) == 1]

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province,update_delta
0,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02 11:49:34+00:00,2017-02-01T18:04:44Z,39.561570,-95.12102,NaN,NaN,2017-02-01T18:04:44Z,NaN,Taco,Gambino's Pizza,KS,336
1,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02 11:49:34+00:00,2017-02-01T18:04:44Z,39.561570,-95.12102,NaN,NaN,2016-03-02T11:49:34Z,"Beef, onion, cheddar cheese, lettuce, refried...",Taco,Gambino's Pizza,KS,336
66,AVwc_59U_7pvs4fz1Md3,3250 Kennedy Cir,"Pizza,Take Out Restaurants,Caterers,Restaurant...",Dubuque,Pizza,2016-03-29 04:45:06+00:00,2016-05-05T12:40:51Z,42.505264,-90.72141,NaN,NaN,"2016-05-05T12:40:51Z,2016-03-29T04:45:06Z",NaN,Taco Supreme,Falbo Bros Pizzeria,IA,37
67,AVwc_59U_7pvs4fz1Md3,3250 Kennedy Cir,"Pizza,Take Out Restaurants,Caterers,Restaurant...",Dubuque,Pizza,2016-03-29 04:45:06+00:00,2016-05-05T12:40:51Z,42.505264,-90.72141,NaN,NaN,"2016-05-05T12:40:51Z,2016-03-29T04:45:06Z",NaN,Taco,Falbo Bros Pizzeria,IA,37
158,AVwc_AmZkufWRAb51FxA,133 Howard St,"Pizza,Restaurants",Braintree,Pizza,2016-09-19 17:43:53+00:00,2016-09-19T17:43:53Z,42.233826,-70.98024,NaN,USD,2016-09-19T17:43:53Z,"Large salsa, pizza cheese, hamburger, hot pepp...",Mexican Taco,New England House of Pizza,Braintree Hld,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76256,AVweVOBFByjofQCxxRnN,3000 N Dinuba Blvd,"Latin American Restaurants,Take Out Restaurant...",Visalia,"Latin American Restaurants,Mexican",2016-07-06 20:48:02+00:00,2016-11-18T15:46:04Z,36.351383,-119.29696,NaN,USD,2016-07-06T20:48:02Z,"Roasted pork, cabbage, cilantro, onion, beans,...",Tacos De Adobado,Figaro's Mexican Grill,CA,134
76291,AVweVXD4ByjofQCxxS7L,35 N Farview Ave,"Italian Restaurant,Pizza Place",Paramus,NaN,2016-03-15 19:34:54+00:00,2016-05-06T20:35:40Z,NaN,NaN,NaN,USD,2016-03-15T19:34:54Z,NaN,Taco,La Bella Roma Pizzeria,NJ,52
76507,AVweWyOEkufWRAb5CNJU,1516 E Historic Highway 66,"Take Out Restaurants,Restaurants,Italian Resta...",Gallup,Take Out Restaurants,2017-01-12 18:46:56+00:00,2017-01-12T18:46:56Z,35.530148,-108.71973,NaN,NaN,2017-01-12T18:46:56Z,"Beef, Whole Beans, Cheddar Cheese, Onion, Lett...",Navajo Taco,Big Cheese Pizza,Pinedale,0
76669,AVweXxalByjofQCxxnWC,1895 Washington Blvd,"Bars,Restaurants,Bar & Grills,Pizza",Ogden,Bars,2016-12-25 18:11:56+00:00,2016-12-25T18:11:56Z,41.233300,-111.97047,NaN,USD,2016-12-25T18:11:56Z,"Our famous chili verde, string potatoes, three...",Chili Verde Breakfast Burrito,Slackwater Pub Pizzeria,Marriott-slaterville City,0
76709,AVweYFH-ByjofQCxxqHG,620 Water St S,"Bars,Pizza,Italian Restaurants,Family Style Re...",Northfield,Bars,2016-04-03 12:15:30+00:00,2016-04-03T12:15:30Z,44.453735,-93.16171,NaN,NaN,2016-04-03T12:15:30Z,"Mild Tomato chili sauce, chipotle beef topped ...",Taco - A South of The Boarder Favorite,Carbone's Pizzeria,MN,0

В этом задании нужно отобрать записи, у которых более 20 категорий, далее их нужно сгруппировать по провинциям и подсчитать минимальную longitude в каждой. Округлите значения longitude до 3-х знаков после запятой.

In [29]:
df[df['categories'].apply(lambda x: len(x.split(',')) > 20)].groupby('province')['longitude'].min()

province
AZ             -110.136168
CA             -122.417190
DC              -77.074610
G P O           -73.990491
KY              -87.454722
MA              -71.055180
MD              -77.452987
NY              -76.793573
St Simons Is    -81.394050
TX              -94.939345
VA              -77.092562
WA             -122.383123
WI              -89.376639
Name: longitude, dtype: float64